# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69cb7052cf547a4b744201fda32cb1c356540b02a854846bbf977f7356d8e9f5f6e389cb4baeccdb321551b54c94c3e997f5bef66031c1388e5cd7c79ca307b9

test:
  secret_key_base: 45d8cc6945f85c952f352f6952db66384565fc5c549528af4da8913a9a083640d44f09814f43e7e869f72b4c24cdc701b8ba4854902b7abbc7ff51d7e5ccd472

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
